version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  dependencies:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: "Npm Install"
          command: npm install --dev

  linter:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: "Run Linter"
          command: npm run lint

  tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: "Check Chrome Install"
      - run:
          name: "Run Tests"
          command: npm run test --no-watch --no-progress --browsers=ChromeHeadless

  build:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: "Build Angular Package"
          command: npm run build

workflows:
  angular-ci:
    jobs:
      - dependencies
      - linter:
          requires:
            - dependencies
      - tests:
          requires:
            - dependencies
      - build:
          requires:
            - linter
            - tests
